// <auto-generated />
using CityInfo.Api.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.Api.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    partial class CityInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("CityInfo.Api.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Quadratestadt wo isch wohne tu",
                            Name = "Mannheim"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Hauptstadt des Landes wo isch lebe tu",
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Hauptstadt von Frankreich",
                            Name = "Paris"
                        });
                });

            modelBuilder.Entity("CityInfo.Api.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointOfInterests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "Wasserturm am Ende der Planken mit einem Park",
                            Name = "Wasserturm"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "Veranstaltungszentrum am Ring",
                            Name = "Rosengarten"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "Demokratie wird hier verbrochen",
                            Name = "Reichstag"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "Großes Tor mit Checkpoint Charlie in der Nähe(?)",
                            Name = "Brandenburger Tor"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "Großer Turm den man besichtigen kann",
                            Name = "Eiffelturm"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Description = "Römisch-katholische Kathedrale",
                            Name = "Notre Dame"
                        });
                });

            modelBuilder.Entity("CityInfo.Api.Entities.PointOfInterest", b =>
                {
                    b.HasOne("CityInfo.Api.Entities.City", "City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfo.Api.Entities.City", b =>
                {
                    b.Navigation("PointsOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
